# Generated by Django 5.2.8 on 2026-01-14 03:41

from django.db import migrations


def add_initial_data(apps, schema_editor):
    Language = apps.get_model("wod", "Language")
    Word = apps.get_model("wod", "Word")

    # Create languages
    english = Language.objects.create(code="en", name="English", is_native=True)
    hungarian = Language.objects.create(code="hu", name="Hungarian", is_native=False)
    german = Language.objects.create(code="de", name="German", is_native=False)

    # Add example Hungarian words
    Word.objects.create(
        language=hungarian,
        word="könyv",
        translation="book",
        definition="A written or printed work consisting of pages bound together",
    )
    Word.objects.create(
        language=hungarian,
        word="ház",
        translation="house",
        definition="A building for human habitation",
    )
    Word.objects.create(
        language=hungarian,
        word="víz",
        translation="water",
        definition="A clear liquid essential for life",
    )

    # Add example German words
    Word.objects.create(
        language=german,
        word="Buch",
        translation="book",
        definition="A written or printed work consisting of pages bound together",
    )
    Word.objects.create(
        language=german,
        word="Haus",
        translation="house",
        definition="A building for human habitation",
    )
    Word.objects.create(
        language=german,
        word="Wasser",
        translation="water",
        definition="A clear liquid essential for life",
    )


def remove_initial_data(apps, schema_editor):
    Language = apps.get_model("wod", "Language")
    Word = apps.get_model("wod", "Word")

    Word.objects.all().delete()
    Language.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("wod", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_initial_data, remove_initial_data),
    ]
