[pytest]
DJANGO_SETTINGS_MODULE = djangolanguage.settings
python_files = tests.py test_*.py *_tests.py
addopts = --nomigrations --cov=. --cov-report=term-missing --cov-report=html -m "not playwright"

markers =
    playwright: marks tests as playwright UI tests (deselect with '-m "not playwright"')
