# Generated by Django 5.2.8 on 2026-01-19 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0002_add_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="definition",
            field=models.TextField(blank=True, default=""),
        ),
    ]
