# Generated by Django 5.2.8 on 2026-01-24 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocabulary", "0006_remove_old_translation_is_native"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="translation",
            new_name="vocabulary__source__7554cf_idx",
            old_name="vocabulary_t_source__idx",
        ),
        migrations.AlterField(
            model_name="word",
            name="definition",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Definition in the same language as the word",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="words",
                to="vocabulary.language",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="word",
            unique_together={("language", "word")},
        ),
    ]
